# Generated by Django 4.2.6 on 2023-11-08 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('number_of_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_plate', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('area', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request', models.CharField(default='', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citizen_identification_card', models.CharField(default='', max_length=30)),
                ('avatar', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('room_bill', models.FloatField(default=0)),
                ('electric_bill', models.FloatField(default=0)),
                ('water_bill', models.FloatField(default=0)),
                ('donate', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('role', models.CharField(default='', max_length=20)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
    ]
