# Generated by Django 4.2.6 on 2023-10-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='donate',
            field=models.FloatField(default=0),
        ),
    ]
