# Generated by Django 4.2.6 on 2023-10-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_donate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persional',
            new_name='Personal',
        ),
    ]
